# Generated by Django 5.2.8 on 2025-11-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=255)),
                ('teacher_id', models.CharField(max_length=255, unique=True)),
                ('temail', models.CharField(max_length=255)),
                ('tdept', models.CharField(max_length=255)),
                ('tassign', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
