# Generated by Django 5.2.8 on 2025-12-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_classteacher_student_marks_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_teacher',
        ),
        migrations.AddField(
            model_name='marks',
            name='class_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student', 'subject')},
        ),
        migrations.DeleteModel(
            name='classteacher',
        ),
    ]
