# Generated by Django 5.2.8 on 2025-12-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_student_class_teacher_marks_class_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together=set(),
        ),
    ]
