# Generated by Django 5.2.8 on 2025-12-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_marks_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='student_name',
        ),
    ]
