# Generated by Django 5.2.8 on 2025-12-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_marks_class_name_remove_marks_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='class_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marks',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student', 'subject')},
        ),
    ]
