# Generated by Django 5.2.8 on 2025-12-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_marks_class_name_marks_student_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together=set(),
        ),
    ]
