# Generated by Django 5.2.8 on 2025-12-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_marks_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], default='morning', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_class',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('student', 'subject')},
        ),
    ]
