# Generated by Django 5.2.8 on 2025-12-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_attendance_session_attendance_student_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Passed_out_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Passed Out', 'Passed Out'), ('TC Issued', 'TC Issued')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='tc_issued_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
