# Generated by Django 5.2.8 on 2025-12-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_student_passed_out_year_student_admission_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Passed_out_year',
            new_name='passed_out_year',
        ),
    ]
