# Generated by Django 5.2.8 on 2025-12-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_rename_passed_out_year_student_passed_out_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Resigned', 'Resigned'), ('Retired', 'REtired')], default='Active', max_length=20),
        ),
    ]
